name: Run main.py

on:
  schedule:
    - cron: '0 0,6,12,18 * * *' # Every 6 hours
    branches:
      - workflows
  push:
    branches:
      - workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Use the latest version of the checkout action

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify the Python version

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py
